#variables for game tuning
window_width = int(640)
window_height = int(480)
snake_size_x = int(20)
snake_size_y = int(20)
snake_starting_speed = int(2)
snake_increment_speed = int(1)
snake_offset = int(20)
food_offset = int(10)
food_size_x = int(10)
food_size_y = int(10)