#variables for game tuning
window_width = int(640)
window_height = int(480)
snake_size = int(20)
snake_speed = int(20)
snake_offset = int(20)
snake_tail_offset = int(21)
food_offset = int(10)
food_size_x = int(10)
food_size_y = int(10)
timer = int(1000)
timer_offset = int(3)